language: elixir
matrix:
  include:
    - elixir: 1.10.4
      otp_release: 22.3.4
    - elixir: 1.11.0
      otp_release: 23.0.4
    - elixir: 1.12.3
      otp_release: 24.0.2
env:
  MIX_ENV=test
script:
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash) # send coverage report
cache:
  directories:
    - _build
    - deps
