name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
    - name: Run Coverage
      run: mix coveralls.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 5e27328a-c381-4998-8ce2-5e84c44284c4
        file: ./cover/excoveralls.json
